"""Constants for the integration."""

DOMAIN = "template_metrics"
USER = "user"
TOKEN = "token"
REMOTE_WRITE_URL = "remote_write_url"
UPDATE_INTERVAL = "update_interval"
METRICS = "metrics"
TEMPLATE_NAME = "name"
TEMPLATE = "template"
METER = "meter"
COORDINATOR = "coordinator"
PROVIDER = "provider"
