"""Constants for the integration."""

DOMAIN = "hametrics"
INSTANCE_ID = "instance_id"
API_KEY = "api_key"
REMOTE_WRITE_URL = "remote_write_url"
UPDATE_INTERVAL = "update_interval"
METRICS = "metrics"
TEMPLATE_NAME = "name"
TEMPLATE = "template"
METER = "meter"
COORDINATOR = "coordinator"
